bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path('account/', include('account.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('images/', include('images.urls', namespace='images')),
    path('__debug__/', include('debug_toolbar.urls')),
    
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

images/urls.py
from django.urls import path
from . import views

app_name = 'images'

urlpatterns = [
    path('create/', views.image_create, name='create'),
    path('detail/<int:id>/<slug:slug>', views.image_detail, name='detail'),
    path('like/', views.image_like, name='like'),
    path('', views.image_list, name='list'),
    path('ranking/', views.image_ranking, name='ranking'),
]

images/models.py
from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.urls import reverse

class Image(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
                             related_name='images_created', on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True)
    url = models.URLField(max_length=2000)
    image = models.ImageField(upload_to='images/%Y/%m/%d')
    total_likes = models.PositiveIntegerField(default=0)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    users_like = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='images_liked', blank=True)


    class Meta:
        indexes = [
            models.Index(fields=['-created']),
            models.Index(fields=['-total_likes'])
        ]
        ordering = ['-created']

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('images:detail', args=[self.id, self.slug])

images/forms.py
from django import forms
from .models import Image
from django.core.files.base import ContentFile
from django.utils.text import slugify
import requests


class ImageCreateForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['title', 'url', 'description']
        widgets = {
            'url': forms.HiddenInput
        }

    def clean_url(self):
        url = self.cleaned_data['url']
        valid_extensions = ['jpeg', 'jpg', 'png']
        extension = url.rsplit('.', 1)[1].lower()
        if extension not in valid_extensions:
            raise forms.ValidationError('The given URL does not match valid image extensions.')
        return url
    
    def save(self, force_insert=False, force_update=False, commit=True):
        image = super().save(commit=False)
        image_url = self.cleaned_data['url']
        name = slugify(image.title)
        extension = image_url.rsplit('.', 1)[1].lower()
        image_name = f'{name}.{extension}'
        response = requests.get(image_url)
        image.image.save(image_name, ContentFile(response.content), save=False)
        if commit:
            image.save()
        return image

images/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from .forms import ImageCreateForm
from django.shortcuts import get_object_or_404
from .models import Image
from django.http import JsonResponse
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action
import redis 
from django.conf import settings

r = redis.Redis(host=settings.REDIS_HOST, port=settings.REDIS_PORT, db=settings.REDIS_DB)

@login_required
def image_create(request):
    if request.method == 'POST':
        form = ImageCreateForm(data=request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_image = form.save(commit=False)
            new_image.user = request.user
            new_image.save()
            create_action(request.user, 'bookmarked image', new_image)
            messages.success(request, 'Image added successfully')
            return redirect(new_image.get_absolute_url())
    else:
        form = ImageCreateForm(data=request.GET)
    return render(request, 'images/image/create.html', 
                  {'section': 'images','form': form})
        

def image_detail(request, id, slug):
    image = get_object_or_404(Image, id=id, slug=slug)
    total_views = r.incr(f'image:{image.id}:views')
    w = r.zincrby('image_rank', 1, image.id)
    print(w)
    return render(request, 'images/image/detail.html', 
                  {'section':'images', 'image': image, 'total_views':total_views})

@login_required
def image_ranking(request):
    image_ranking = r.zrange('image_ranking', 0, -1, desc=True)[:10]
    print(image_ranking)
    image_ranking_ids = [int(id) for id in image_ranking]
    most_viewed = list(Image.objects.filter(id__in=image_ranking_ids))
    most_viewed.sort(key=lambda x: image_ranking_ids.index(x.id))
    return render(request,'images/image/ranking.html', 
                  {'section': 'images','most_viewed': most_viewed})


@login_required
@require_POST
def image_like(request):
    image_id = request.POST.get('id')
    action = request.POST.get('action')

    if image_id and action:
        try:
            image = Image.objects.get(id=image_id)
            if action == 'like':
                image.users_like.add(request.user)
                create_action(request.user, 'likes', image)
            else:
                image.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except Image.DoesNotExist:
            pass
    return JsonResponse({'status': 'error'})



@login_required
def image_list(request):
    images = Image.objects.all()
    paginator = Paginator(images, 8)
    page = request.GET.get('page')
    images_only = request.GET.get('images_only')
    try:
        images = paginator.page(page)
    except PageNotAnInteger:
        images = paginator.page(1)
    except EmptyPage:
        if images_only:
            return HttpResponse('')
        images = paginator.page(paginator.num_pages)
    if images_only:
        return render(request, 'images/image/list_images.html', {'section': 'images', 'images':images})
    return render(request, 'images/image/list.html', {'section': 'images', 'images':images})

images/templates/images/image/create.html
{% extends "base.html" %}
{% block title %}Bookmark an image{% endblock %}
{% block content %}
<h1>Bookmark an image</h1>
<img src="{{ request.GET.url }}" class="image-preview">
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Bookmark it!">
</form>
{% endblock %}

images/templates/images/image/detail.html
{% extends "base.html" %}
{% block title %}{{ image.title }}{% endblock %}
{% block content %}
<h1>{{ image.title }}</h1>
{% load thumbnail %}
<a href="{{ image.image.url }}">
    <img src="{% thumbnail image.image 300x0 %}" class="image-detail">
</a>
{% with total_likes=image.users_like.count users_like=image.users_like.all %}
<div class="image-info">
    <div>
        <span class="count">
            <span class="total">{{ total_likes }}</span>
            like{{ total_likes|pluralize }}
        </span>
        <span class="count">
            {{ total_views }} view{{ total_views|pluralize }}
        </span>
        <a href="#" data-id="{{ image.id }}" data-action="{% if request.user in users_like %}un{% endif %}like" class="like button">
            {% if request.user not in users_like %}
            Like
            {% else %}
            Unlike
            {% endif %}
        </a>
    </div>
    {{ image.description|linebreaks }}
</div>
<div class="image-likes">
    {% for user in users_like %}
    <div>
        {% if user.profile.photo %}
        <img src="{{ user.profile.photo.url }}">
        {% endif %}
        <p>{{ user.first_name }}</p>
    </div>
    {% empty %}Nobody likes this image yet.
    {% endfor %}
    </div>
    {% endwith %}
{% endblock %}

{% block domready %}
const url = '{% url "images:like" %}';

var options = {
method: 'POST',
headers: {'X-CSRFToken': csrftoken},
mode: 'same-origin'
}

document.querySelector('a.like')
.addEventListener('click', function(e){
e.preventDefault();
var likeButton = this;

// add request body
var formData = new FormData();
formData.append('id', likeButton.dataset.id);
formData.append('action', likeButton.dataset.action);
options['body'] = formData;

// send HTTP request
fetch(url, options)
.then(response => response.json())
.then(data => {
if (data['status'] === 'ok')
{
    var previousAction = likeButton.dataset.action;

    // toggle button text and data-action
    var action = previousAction === 'like' ? 'unlike' : 'like';
    likeButton.dataset.action = action;
    likeButton.innerHTML = action;

    // update like count
    var likeCount = document.querySelector('span.count .total');
    var totalLikes = parseInt(likeCount.innerHTML);

    likeCount.innerHTML = previousAction === 'like' ? totalLikes + 1 : totalLikes - 1;
}
})
});

{% endblock %}

images/templates/images/image/list.html
{% extends "base.html" %}
{% block title %}Images bookmarked{% endblock %}
{% block content %}
<h1>Images bookmarked</h1>
<div id="image-list">
    {% include "images/image/list_images.html" %}
</div>
{% endblock %}

{% block domready %}
var page = 1;
var emptyPage = false;
var blockRequest = false;

window.addEventListener('scroll', function(e) {
var margin = document.body.clientHeight - window.innerHeight - 200;
if(window.pageYOffset > margin && !emptyPage && !blockRequest) {
blockRequest = true;
page += 1;

fetch('?images_only=1&page=' + page)
.then(response => response.text())
.then(html => {
if (html === '') {
emptyPage = true;
}
else {
var imageList = document.getElementById('image-list');
imageList.insertAdjacentHTML('beforeEnd', html);
blockRequest = false;
}
})
}
});

// Launch scroll event
const scrollEvent = new Event('scroll');
window.dispatchEvent(scrollEvent);
{% endblock %}

images/templates/images/image/list_images.html
{% load thumbnail %}
{% for image in images %}
<div class="image">
    <a href="{{ image.get_absolute_url }}">
        {% thumbnail image.image 300x300 crop="smart" as im %}
        <a href="{{ image.get_absolute_url }}">
            <img src="{{ im.url }}">
        </a>
    </a>
    <div class="info">
        <a href="{{ image.get_absolute_url }}" class="title">
            {{ image.title }}
        </a>
    </div>
</div>
{% endfor %}

images/templates/images/image/ranking.html
{% extends "base.html" %}
{% block title %}Images ranking{% endblock %}
{% block content %}
<h1>Images ranking</h1>
<ol>
    {% for image in most_viewed %}
    <li>
        <a href="{{ image.get_absolute_url }}">
            {{ image.title }}
        </a>
    </li>
    {% endfor %}
</ol>
{% endblock %}